# Generated by Django 4.1.3 on 2022-11-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
