# Generated by Django 4.1.3 on 2022-11-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_attribute_filterinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterinfo',
            name='show',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='filterinfo',
            name='value',
            field=models.CharField(help_text='Значение', max_length=255),
        ),
    ]
