# Generated by Django 4.1.3 on 2022-11-15 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_filterinfo_show_alter_filterinfo_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='attributes',
            field=models.ManyToManyField(related_name='attributes', through='catalog.FilterInfo', to='catalog.attribute'),
        ),
        migrations.AlterField(
            model_name='filterinfo',
            name='rel_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attribute'),
        ),
        migrations.AlterField(
            model_name='filterinfo',
            name='rel_fish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.fish'),
        ),
    ]
