# Generated by Django 4.1.3 on 2022-11-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='CreateDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='UpdateDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='CreateDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='UpdateDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='CreateDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='UpdateDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='CreateDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='UpdateDate',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите ваше имя', max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.fish')),
            ],
        ),
    ]
