# Generated by Django 4.1.3 on 2022-11-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_attribute_createdate_attribute_updatedate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите ваше имя', max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/comms/%Y/%m/%d/')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.fish')),
            ],
        ),
        migrations.DeleteModel(
            name='comments',
        ),
    ]
