# Generated by Django 4.1.3 on 2022-11-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_feedback_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название локации', max_length=255)),
                ('adress', models.CharField(help_text='Адрес', max_length=255)),
                ('number', models.CharField(help_text='Номер телефона', max_length=255)),
                ('email', models.CharField(help_text='Адрес электронной почты', max_length=255)),
            ],
        ),
    ]
