# Generated by Django 4.1.3 on 2022-11-18 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_location_options_location_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collback_requst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Указанное имя', max_length=255)),
                ('number', models.CharField(help_text='Номер телефона', max_length=255)),
                ('email', models.CharField(blank=True, help_text='Адрес электронной почты', max_length=255, null=True)),
                ('text', models.TextField()),
                ('CreateDate', models.DateField(null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.location')),
            ],
        ),
    ]
