# Generated by Django 4.1.3 on 2022-11-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_collback_requst'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='CreateDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='UpdateDate',
            field=models.DateField(null=True),
        ),
    ]
