# Generated by Django 4.1.3 on 2022-11-18 12:12

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_location_createdate_location_updatedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback_requst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Указанное имя', max_length=255)),
                ('phone', phone_field.models.PhoneField(help_text='Ваш номер телефона', max_length=31)),
                ('email', models.CharField(blank=True, help_text='Адрес электронной почты', max_length=255, null=True)),
                ('text', models.TextField()),
                ('CreateDate', models.DateField(null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.location')),
            ],
        ),
        migrations.DeleteModel(
            name='Collback_requst',
        ),
    ]
