# Generated by Django 4.1.3 on 2022-11-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_callback_requst_delete_collback_requst'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Callback_requst',
            new_name='Callback_request',
        ),
    ]
