# Generated by Django 4.1.3 on 2022-11-18 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_rename_callback_requst_callback_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback_request',
            name='CreateDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
