# Generated by Django 4.1.3 on 2022-11-18 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_callback_request_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='CreateDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='category',
            name='CreateDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='fish',
            name='CreateDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='location',
            name='CreateDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
