# Generated by Django 4.1.3 on 2022-11-21 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_callback_request_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback_request',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.location'),
        ),
    ]
