# Generated by Django 4.1.3 on 2022-11-21 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_feedback_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_generic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите ваше имя', max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/comms/%Y/%m/%d/')),
            ],
        ),
    ]
