# Generated by Django 4.1.3 on 2022-11-25 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_feedback_generic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filterinfo',
            options={'ordering': ['rel_attribute']},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='CreateDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='UpdateDate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='callback_request',
            name='CreateDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='CreateDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='UpdateDate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedback_generic',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='CreateDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='UpdateDate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='CreateDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='UpdateDate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='CreateDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='UpdateDate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
