# Generated by Django 4.1.3 on 2022-11-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_alter_filterinfo_options_alter_attribute_createdate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fish',
            options={'ordering': ['-UpdateDate']},
        ),
    ]
