# Generated by Django 4.1.3 on 2022-11-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
    ]
