# Generated by Django 4.1.3 on 2022-11-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_good_price_alter_good_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название товара', max_length=250)),
                ('location', models.CharField(blank=True, choices=[('Б', 'Балтика'), ('А', 'Атлантический океан'), ('Л', 'Лужа'), ('У', 'АквариУм')], help_text='Выберите источник рыбы', max_length=1)),
                ('price', models.IntegerField(help_text='Введите стоимость рыбы', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Введите категорию', max_length=250),
        ),
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category'),
        ),
    ]
