# Generated by Django 4.1.3 on 2022-11-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
